"use strict";
exports.__esModule = true;
exports.NEBULA_PINK_DARK = exports.NEBULA_PINK_BASE = exports.NEBULA_PINK_LIGHT = exports.NEBULA_PINK_XLIGHT = exports.MYSTIC_BLUE = exports.MYSTIC_BLUE_DARK = exports.MYSTIC_BLUE_BASE = exports.MYSTIC_BLUE_LIGHT = exports.MYSTIC_BLUE_XLIGHT = exports.LUNA_YELLOW = exports.LUNA_YELLOW_DARK = exports.LUNA_YELLOW_BASE = exports.LUNA_YELLOW_LIGHT = exports.LUNA_YELLOW_XLIGHT = exports.FLORIDA_ORGANCE = exports.FLORIDA_ORGANCE_DARK = exports.FLORIDA_ORGANCE_BASE = exports.FLORIDA_ORGANCE_LIGHT = exports.FLORIDA_ORGANCE_XLIGHT = exports.COSMIC_PURPLE = exports.COSMIC_PURPLE_DARK = exports.COSMIC_PURPLE_BASE = exports.COSMIC_PURPLE_LIGHT = exports.COSMIC_PURPLE_XLIGHT = exports.CELESTIAL_BLUE = exports.CELESTIAL_BLUE_DARK = exports.CELESTIAL_BLUE_BASE = exports.CELESTIAL_BLUE_LIGHT = exports.CELESTIAL_BLUE_XLIGHT = exports.MISSION_RED = exports.MISSION_RED_DARK = exports.MISSION_RED_BASE = exports.MISSION_RED_LIGHT = exports.MISSION_RED_XLIGHT = exports.ML2_PURPLE_DARK = exports.ML2_PURPLE_BASE = exports.ML2_PURPLE_LIGHT = exports.ML2_PURPLE_XLIGHT = exports.DEFAULT_BACKGROUND = exports.BLACK = exports.WHITE = exports.XXLIGHT = exports.XLIGHT = exports.LIGHT = exports.MEDIUM = exports.BASE = exports.DARK = exports.XDARK = exports.XXDARK = exports.XXXDARK = void 0;
exports.TATOOINE_GREEN = exports.TATOOINE_GREEN_DARK = exports.TATOOINE_GREEN_BASE = exports.TATOOINE_GREEN_LIGHT = exports.TATOOINE_GREEN_XLIGHT = exports.SECONDARY_ORANGE = exports.SECONDARY_ORANGE_DARK = exports.SECONDARY_ORANGE_BASE = exports.SECONDARY_ORANGE_LIGHT = exports.SECONDARY_ORANGE_XLIGHT = exports.NEBULA_PINK = void 0;
// BASE
exports.XXXDARK = "#1A1A1A";
exports.XXDARK = "#2A2A2A";
exports.XDARK = "#4A4A4A";
exports.DARK = "#717171";
exports.BASE = "#5C5D60";
exports.MEDIUM = "#ABAEB1";
exports.LIGHT = "#D6D6D6";
exports.XLIGHT = "#E6E6E6";
exports.XXLIGHT = "#F8F8F8";
exports.WHITE = "#FFFFFF";
exports.BLACK = "#000000";
// BACKGROUND
exports.DEFAULT_BACKGROUND = "#EEE";
// ML2_PURPLE
exports.ML2_PURPLE_XLIGHT = "#8e6edd"; // base lightened by 20%
exports.ML2_PURPLE_LIGHT = "#6d45d3"; // base lightened by 10%
exports.ML2_PURPLE_BASE = "#532CB9";
exports.ML2_PURPLE_DARK = "#412291"; // base darkened by 10%
// MISSION_RED
exports.MISSION_RED_XLIGHT = "#F12742";
exports.MISSION_RED_LIGHT = "#F12742";
exports.MISSION_RED_BASE = "#F12742";
exports.MISSION_RED_DARK = "#F12742";
exports.MISSION_RED = {
    xLight: exports.MISSION_RED_XLIGHT,
    light: exports.MISSION_RED_LIGHT,
    base: exports.MISSION_RED_BASE,
    dark: exports.MISSION_RED_DARK
};
// CELESTIAL_BLUE
exports.CELESTIAL_BLUE_XLIGHT = "#b3d2f2";
exports.CELESTIAL_BLUE_LIGHT = "#8dbceb";
exports.CELESTIAL_BLUE_BASE = "#67a5e5";
exports.CELESTIAL_BLUE_DARK = "#418fde";
exports.CELESTIAL_BLUE = {
    xLight: exports.CELESTIAL_BLUE_XLIGHT,
    light: exports.CELESTIAL_BLUE_LIGHT,
    base: exports.CELESTIAL_BLUE_BASE,
    dark: exports.CELESTIAL_BLUE_DARK
};
// COSMIC_PURPLE
exports.COSMIC_PURPLE_XLIGHT = "#f1d7f2";
exports.COSMIC_PURPLE_LIGHT = "#ebc4ec";
exports.COSMIC_PURPLE_BASE = "#e4b0e5";
exports.COSMIC_PURPLE_DARK = "#dd9cdf";
exports.COSMIC_PURPLE = {
    xLight: exports.COSMIC_PURPLE_XLIGHT,
    light: exports.COSMIC_PURPLE_LIGHT,
    base: exports.COSMIC_PURPLE_BASE,
    dark: exports.COSMIC_PURPLE_DARK
};
// FLORIDA_ORGANCE
exports.FLORIDA_ORGANCE_XLIGHT = "#f3b8b0";
exports.FLORIDA_ORGANCE_LIGHT = "#ec9588";
exports.FLORIDA_ORGANCE_BASE = "#e67161";
exports.FLORIDA_ORGANCE_DARK = "#e04e39";
exports.FLORIDA_ORGANCE = {
    xLight: exports.FLORIDA_ORGANCE_XLIGHT,
    light: exports.FLORIDA_ORGANCE_LIGHT,
    base: exports.FLORIDA_ORGANCE_BASE,
    dark: exports.FLORIDA_ORGANCE_DARK
};
// LUNA_YELLOW
exports.LUNA_YELLOW_XLIGHT = "#fcf7b6";
exports.LUNA_YELLOW_LIGHT = "#faf291";
exports.LUNA_YELLOW_BASE = "#f9ee6d";
exports.LUNA_YELLOW_DARK = "#f7ea48";
exports.LUNA_YELLOW = {
    xLight: exports.LUNA_YELLOW_XLIGHT,
    light: exports.LUNA_YELLOW_LIGHT,
    base: exports.LUNA_YELLOW_BASE,
    dark: exports.LUNA_YELLOW_DARK
};
// MYSTIC_BLUE
exports.MYSTIC_BLUE_XLIGHT = "#dbf1f6";
exports.MYSTIC_BLUE_LIGHT = "#c8e9f1";
exports.MYSTIC_BLUE_BASE = "#b6e2ed";
exports.MYSTIC_BLUE_DARK = "#a4dbe8";
exports.MYSTIC_BLUE = {
    xLight: exports.MYSTIC_BLUE_XLIGHT,
    light: exports.MYSTIC_BLUE_LIGHT,
    base: exports.MYSTIC_BLUE_BASE,
    dark: exports.MYSTIC_BLUE_DARK
};
// NEBULA_PINK
exports.NEBULA_PINK_XLIGHT = "#f2a3d5";
exports.NEBULA_PINK_LIGHT = "#ec75bf";
exports.NEBULA_PINK_BASE = "#e547aa";
exports.NEBULA_PINK_DARK = "#df1995";
exports.NEBULA_PINK = {
    xLight: exports.NEBULA_PINK_XLIGHT,
    light: exports.NEBULA_PINK_LIGHT,
    base: exports.NEBULA_PINK_BASE,
    dark: exports.NEBULA_PINK_DARK
};
// SECONDARY_ORANGE
exports.SECONDARY_ORANGE_XLIGHT = "#ffd6ba";
exports.SECONDARY_ORANGE_LIGHT = "#ffc297";
exports.SECONDARY_ORANGE_BASE = "#ffad75";
exports.SECONDARY_ORANGE_DARK = "#ff9952";
exports.SECONDARY_ORANGE = {
    xLight: exports.SECONDARY_ORANGE_XLIGHT,
    light: exports.SECONDARY_ORANGE_LIGHT,
    base: exports.SECONDARY_ORANGE_BASE,
    dark: exports.SECONDARY_ORANGE_DARK
};
// TATOOINE_GREEN
exports.TATOOINE_GREEN_XLIGHT = "#a8eccb";
exports.TATOOINE_GREEN_LIGHT = "#7de3b0";
exports.TATOOINE_GREEN_BASE = "#51da96";
exports.TATOOINE_GREEN_DARK = "#26d07c";
exports.TATOOINE_GREEN = {
    xLight: exports.TATOOINE_GREEN_XLIGHT,
    light: exports.TATOOINE_GREEN_LIGHT,
    base: exports.TATOOINE_GREEN_BASE,
    dark: exports.TATOOINE_GREEN_DARK
};
exports["default"] = {
    XDARK: exports.XDARK,
    DARK: exports.DARK,
    BASE: exports.BASE,
    LIGHT: exports.LIGHT,
    XLIGHT: exports.XLIGHT,
    XXLIGHT: exports.XXLIGHT,
    WHITE: exports.WHITE,
    BLACK: exports.BLACK,
    ML2_PURPLE_XLIGHT: exports.ML2_PURPLE_XLIGHT,
    ML2_PURPLE_LIGHT: exports.ML2_PURPLE_LIGHT,
    ML2_PURPLE_BASE: exports.ML2_PURPLE_BASE,
    ML2_PURPLE_DARK: exports.ML2_PURPLE_DARK,
    MISSION_RED_XLIGHT: exports.MISSION_RED_XLIGHT,
    MISSION_RED_LIGHT: exports.MISSION_RED_LIGHT,
    MISSION_RED_BASE: exports.MISSION_RED_BASE,
    MISSION_RED_DARK: exports.MISSION_RED_DARK,
    MISSION_RED: exports.MISSION_RED,
    CELESTIAL_BLUE_XLIGHT: exports.CELESTIAL_BLUE_XLIGHT,
    CELESTIAL_BLUE_LIGHT: exports.CELESTIAL_BLUE_LIGHT,
    CELESTIAL_BLUE_BASE: exports.CELESTIAL_BLUE_BASE,
    CELESTIAL_BLUE_DARK: exports.CELESTIAL_BLUE_DARK,
    CELESTIAL_BLUE: exports.CELESTIAL_BLUE,
    COSMIC_PURPLE_XLIGHT: exports.COSMIC_PURPLE_XLIGHT,
    COSMIC_PURPLE_LIGHT: exports.COSMIC_PURPLE_LIGHT,
    COSMIC_PURPLE_BASE: exports.COSMIC_PURPLE_BASE,
    COSMIC_PURPLE_DARK: exports.COSMIC_PURPLE_DARK,
    COSMIC_PURPLE: exports.COSMIC_PURPLE,
    FLORIDA_ORGANCE_XLIGHT: exports.FLORIDA_ORGANCE_XLIGHT,
    FLORIDA_ORGANCE_LIGHT: exports.FLORIDA_ORGANCE_LIGHT,
    FLORIDA_ORGANCE_BASE: exports.FLORIDA_ORGANCE_BASE,
    FLORIDA_ORGANCE_DARK: exports.FLORIDA_ORGANCE_DARK,
    FLORIDA_ORGANCE: exports.FLORIDA_ORGANCE,
    LUNA_YELLOW_XLIGHT: exports.LUNA_YELLOW_XLIGHT,
    LUNA_YELLOW_LIGHT: exports.LUNA_YELLOW_LIGHT,
    LUNA_YELLOW_BASE: exports.LUNA_YELLOW_BASE,
    LUNA_YELLOW_DARK: exports.LUNA_YELLOW_DARK,
    LUNA_YELLOW: exports.LUNA_YELLOW,
    MYSTIC_BLUE_XLIGHT: exports.MYSTIC_BLUE_XLIGHT,
    MYSTIC_BLUE_LIGHT: exports.MYSTIC_BLUE_LIGHT,
    MYSTIC_BLUE_BASE: exports.MYSTIC_BLUE_BASE,
    MYSTIC_BLUE_DARK: exports.MYSTIC_BLUE_DARK,
    MYSTIC_BLUE: exports.MYSTIC_BLUE,
    NEBULA_PINK_XLIGHT: exports.NEBULA_PINK_XLIGHT,
    NEBULA_PINK_LIGHT: exports.NEBULA_PINK_LIGHT,
    NEBULA_PINK_BASE: exports.NEBULA_PINK_BASE,
    NEBULA_PINK_DARK: exports.NEBULA_PINK_DARK,
    NEBULA_PINK: exports.NEBULA_PINK,
    SECONDARY_ORANGE_XLIGHT: exports.SECONDARY_ORANGE_XLIGHT,
    SECONDARY_ORANGE_LIGHT: exports.SECONDARY_ORANGE_LIGHT,
    SECONDARY_ORANGE_BASE: exports.SECONDARY_ORANGE_BASE,
    SECONDARY_ORANGE_DARK: exports.SECONDARY_ORANGE_DARK,
    SECONDARY_ORANGE: exports.SECONDARY_ORANGE,
    TATOOINE_GREEN_XLIGHT: exports.TATOOINE_GREEN_XLIGHT,
    TATOOINE_GREEN_LIGHT: exports.TATOOINE_GREEN_LIGHT,
    TATOOINE_GREEN_BASE: exports.TATOOINE_GREEN_BASE,
    TATOOINE_GREEN_DARK: exports.TATOOINE_GREEN_DARK,
    TATOOINE_GREEN: exports.TATOOINE_GREEN
};
