export declare const XXXDARK = "#1A1A1A";
export declare const XXDARK = "#2A2A2A";
export declare const XDARK = "#4A4A4A";
export declare const DARK = "#717171";
export declare const BASE = "#5C5D60";
export declare const MEDIUM = "#ABAEB1";
export declare const LIGHT = "#D6D6D6";
export declare const XLIGHT = "#E6E6E6";
export declare const XXLIGHT = "#F8F8F8";
export declare const WHITE = "#FFFFFF";
export declare const BLACK = "#000000";
export declare const DEFAULT_BACKGROUND = "#EEE";
export declare const ML2_PURPLE_XLIGHT = "#8e6edd";
export declare const ML2_PURPLE_LIGHT = "#6d45d3";
export declare const ML2_PURPLE_BASE = "#532CB9";
export declare const ML2_PURPLE_DARK = "#412291";
export declare const MISSION_RED_XLIGHT = "#F12742";
export declare const MISSION_RED_LIGHT = "#F12742";
export declare const MISSION_RED_BASE = "#F12742";
export declare const MISSION_RED_DARK = "#F12742";
export declare const MISSION_RED: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const CELESTIAL_BLUE_XLIGHT = "#b3d2f2";
export declare const CELESTIAL_BLUE_LIGHT = "#8dbceb";
export declare const CELESTIAL_BLUE_BASE = "#67a5e5";
export declare const CELESTIAL_BLUE_DARK = "#418fde";
export declare const CELESTIAL_BLUE: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const COSMIC_PURPLE_XLIGHT = "#f1d7f2";
export declare const COSMIC_PURPLE_LIGHT = "#ebc4ec";
export declare const COSMIC_PURPLE_BASE = "#e4b0e5";
export declare const COSMIC_PURPLE_DARK = "#dd9cdf";
export declare const COSMIC_PURPLE: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const FLORIDA_ORGANCE_XLIGHT = "#f3b8b0";
export declare const FLORIDA_ORGANCE_LIGHT = "#ec9588";
export declare const FLORIDA_ORGANCE_BASE = "#e67161";
export declare const FLORIDA_ORGANCE_DARK = "#e04e39";
export declare const FLORIDA_ORGANCE: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const LUNA_YELLOW_XLIGHT = "#fcf7b6";
export declare const LUNA_YELLOW_LIGHT = "#faf291";
export declare const LUNA_YELLOW_BASE = "#f9ee6d";
export declare const LUNA_YELLOW_DARK = "#f7ea48";
export declare const LUNA_YELLOW: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const MYSTIC_BLUE_XLIGHT = "#dbf1f6";
export declare const MYSTIC_BLUE_LIGHT = "#c8e9f1";
export declare const MYSTIC_BLUE_BASE = "#b6e2ed";
export declare const MYSTIC_BLUE_DARK = "#a4dbe8";
export declare const MYSTIC_BLUE: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const NEBULA_PINK_XLIGHT = "#f2a3d5";
export declare const NEBULA_PINK_LIGHT = "#ec75bf";
export declare const NEBULA_PINK_BASE = "#e547aa";
export declare const NEBULA_PINK_DARK = "#df1995";
export declare const NEBULA_PINK: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const SECONDARY_ORANGE_XLIGHT = "#ffd6ba";
export declare const SECONDARY_ORANGE_LIGHT = "#ffc297";
export declare const SECONDARY_ORANGE_BASE = "#ffad75";
export declare const SECONDARY_ORANGE_DARK = "#ff9952";
export declare const SECONDARY_ORANGE: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
export declare const TATOOINE_GREEN_XLIGHT = "#a8eccb";
export declare const TATOOINE_GREEN_LIGHT = "#7de3b0";
export declare const TATOOINE_GREEN_BASE = "#51da96";
export declare const TATOOINE_GREEN_DARK = "#26d07c";
export declare const TATOOINE_GREEN: {
    xLight: string;
    light: string;
    base: string;
    dark: string;
};
declare const _default: {
    XDARK: string;
    DARK: string;
    BASE: string;
    LIGHT: string;
    XLIGHT: string;
    XXLIGHT: string;
    WHITE: string;
    BLACK: string;
    ML2_PURPLE_XLIGHT: string;
    ML2_PURPLE_LIGHT: string;
    ML2_PURPLE_BASE: string;
    ML2_PURPLE_DARK: string;
    MISSION_RED_XLIGHT: string;
    MISSION_RED_LIGHT: string;
    MISSION_RED_BASE: string;
    MISSION_RED_DARK: string;
    MISSION_RED: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    CELESTIAL_BLUE_XLIGHT: string;
    CELESTIAL_BLUE_LIGHT: string;
    CELESTIAL_BLUE_BASE: string;
    CELESTIAL_BLUE_DARK: string;
    CELESTIAL_BLUE: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    COSMIC_PURPLE_XLIGHT: string;
    COSMIC_PURPLE_LIGHT: string;
    COSMIC_PURPLE_BASE: string;
    COSMIC_PURPLE_DARK: string;
    COSMIC_PURPLE: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    FLORIDA_ORGANCE_XLIGHT: string;
    FLORIDA_ORGANCE_LIGHT: string;
    FLORIDA_ORGANCE_BASE: string;
    FLORIDA_ORGANCE_DARK: string;
    FLORIDA_ORGANCE: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    LUNA_YELLOW_XLIGHT: string;
    LUNA_YELLOW_LIGHT: string;
    LUNA_YELLOW_BASE: string;
    LUNA_YELLOW_DARK: string;
    LUNA_YELLOW: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    MYSTIC_BLUE_XLIGHT: string;
    MYSTIC_BLUE_LIGHT: string;
    MYSTIC_BLUE_BASE: string;
    MYSTIC_BLUE_DARK: string;
    MYSTIC_BLUE: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    NEBULA_PINK_XLIGHT: string;
    NEBULA_PINK_LIGHT: string;
    NEBULA_PINK_BASE: string;
    NEBULA_PINK_DARK: string;
    NEBULA_PINK: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    SECONDARY_ORANGE_XLIGHT: string;
    SECONDARY_ORANGE_LIGHT: string;
    SECONDARY_ORANGE_BASE: string;
    SECONDARY_ORANGE_DARK: string;
    SECONDARY_ORANGE: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
    TATOOINE_GREEN_XLIGHT: string;
    TATOOINE_GREEN_LIGHT: string;
    TATOOINE_GREEN_BASE: string;
    TATOOINE_GREEN_DARK: string;
    TATOOINE_GREEN: {
        xLight: string;
        light: string;
        base: string;
        dark: string;
    };
};
export default _default;
