declare const MUI_STYLE_OVERRIDES: {
    MuiAppBar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").AppBarClassKey, {}>>;
    MuiAvatar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").AvatarClassKey, {}>>;
    MuiBackdrop?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").BackdropClassKey, {}>>;
    MuiBadge?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").BadgeClassKey, {}>>;
    MuiBottomNavigation?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiBottomNavigationAction?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").BottomNavigationActionClassKey, {}>>;
    MuiBreadcrumbs?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").BreadcrumbsClassKey, {}>>;
    MuiButton?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ButtonClassKey, {}>>;
    MuiButtonBase?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ButtonBaseClassKey, {}>>;
    MuiButtonGroup?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ButtonGroupClassKey, {}>>;
    MuiCard?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiCardActionArea?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CardActionAreaClassKey, {}>>;
    MuiCardActions?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CardActionsClassKey, {}>>;
    MuiCardContent?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiCardHeader?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CardHeaderClassKey, {}>>;
    MuiCardMedia?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CardMediaClassKey, {}>>;
    MuiCheckbox?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CheckboxClassKey, {}>>;
    MuiChip?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ChipClassKey, {}>>;
    MuiCircularProgress?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CircularProgressClassKey, {}>>;
    MuiCollapse?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").CollapseClassKey, {}>>;
    MuiContainer?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ContainerClassKey, {}>>;
    MuiCssBaseline?: Partial<import("@material-ui/core").StyleRules<"@global", {}>> & {
        '@global'?: {
            '@font-face'?: (import("csstype").FontFace & {
                fallbacks?: import("csstype").FontFace[];
            }) | (import("csstype").FontFace & {
                fallbacks?: import("csstype").FontFace[];
            })[];
        } & Record<string, (import("csstype").FontFace & {
            fallbacks?: import("csstype").FontFace[];
        }) | (import("csstype").FontFace & {
            fallbacks?: import("csstype").FontFace[];
        })[] | import("@material-ui/styles").CSSProperties>;
    };
    MuiDialog?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").DialogClassKey, {}>>;
    MuiDialogActions?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").DialogActionsClassKey, {}>>;
    MuiDialogContent?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").DialogContentClassKey, {}>>;
    MuiDialogContentText?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiDialogTitle?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiDivider?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").DividerClassKey, {}>>;
    MuiDrawer?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").DrawerClassKey, {}>>;
    MuiAccordion?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").AccordionClassKey, {}>>;
    MuiAccordionActions?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").AccordionActionsClassKey, {}>>;
    MuiAccordionDetails?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiAccordionSummary?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").AccordionSummaryClassKey, {}>>;
    MuiExpansionPanel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ExpansionPanelClassKey, {}>>;
    MuiExpansionPanelActions?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ExpansionPanelActionsClassKey, {}>>;
    MuiExpansionPanelDetails?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiExpansionPanelSummary?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ExpansionPanelSummaryClassKey, {}>>;
    MuiFab?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FabClassKey, {}>>;
    MuiFilledInput?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FilledInputClassKey, {}>>;
    MuiFormControl?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FormControlClassKey, {}>>;
    MuiFormControlLabel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FormControlLabelClassKey, {}>>;
    MuiFormGroup?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FormGroupClassKey, {}>>;
    MuiFormHelperText?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FormHelperTextClassKey, {}>>;
    MuiFormLabel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").FormLabelClassKey, {}>>;
    MuiGrid?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").GridClassKey, {}>>;
    MuiGridList?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiGridListTile?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").GridListTileClassKey, {}>>;
    MuiGridListTileBar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").GridListTileBarClassKey, {}>>;
    MuiIcon?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").IconClassKey, {}>>;
    MuiIconButton?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").IconButtonClassKey, {}>>;
    MuiInput?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").InputClassKey, {}>>;
    MuiInputAdornment?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").InputAdornmentClassKey, {}>>;
    MuiInputBase?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").InputBaseClassKey, {}>>;
    MuiInputLabel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").InputLabelClassKey, {}>>;
    MuiLinearProgress?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").LinearProgressClassKey, {}>>;
    MuiLink?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").LinkClassKey, {}>>;
    MuiList?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListClassKey, {}>>;
    MuiListItem?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListItemClassKey, {}>>;
    MuiListItemAvatar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListItemAvatarClassKey, {}>>;
    MuiListItemIcon?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListItemIconClassKey, {}>>;
    MuiListItemSecondaryAction?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiListItemText?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListItemTextClassKey, {}>>;
    MuiListSubheader?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ListSubheaderClassKey, {}>>;
    MuiMenu?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").MenuClassKey, {}>>;
    MuiMenuItem?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").MenuItemClassKey, {}>>;
    MuiMobileStepper?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").MobileStepperClassKey, {}>>;
    MuiNativeSelect?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").NativeSelectClassKey, {}>>;
    MuiOutlinedInput?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").OutlinedInputClassKey, {}>>;
    MuiPaper?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").PaperClassKey, {}>>;
    MuiPopover?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").PopoverClassKey, {}>>;
    MuiRadio?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").RadioClassKey, {}>>;
    MuiScopedCssBaseline?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiSelect?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SelectClassKey, {}>>;
    MuiSlider?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SliderClassKey, {}>>;
    MuiSnackbar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SnackbarClassKey, {}>>;
    MuiSnackbarContent?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SnackbarContentClassKey, {}>>;
    MuiStep?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepClasskey, {}>>;
    MuiStepButton?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepButtonClasskey, {}>>;
    MuiStepConnector?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepConnectorClasskey, {}>>;
    MuiStepContent?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepContentClasskey, {}>>;
    MuiStepIcon?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepIconClasskey, {}>>;
    MuiStepLabel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepLabelClasskey, {}>>;
    MuiStepper?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").StepperClasskey, {}>>;
    MuiSvgIcon?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SvgIconClassKey, {}>>;
    MuiSwitch?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").SwitchClassKey, {}>>;
    MuiTab?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TabClassKey, {}>>;
    MuiTable?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TableClassKey, {}>>;
    MuiTableBody?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiTableCell?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TableCellClassKey, {}>>;
    MuiTableContainer?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiTableFooter?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiTableHead?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiTablePagination?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TablePaginationClassKey, {}>>;
    MuiTableRow?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TableRowClassKey, {}>>;
    MuiTableSortLabel?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TableSortLabelClassKey, {}>>;
    MuiTabs?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TabsClassKey, {}>>;
    MuiTextField?: Partial<import("@material-ui/core").StyleRules<"root", {}>>;
    MuiToolbar?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").ToolbarClassKey, {}>>;
    MuiTooltip?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TooltipClassKey, {}>>;
    MuiTouchRipple?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core/ButtonBase/TouchRipple").TouchRippleClassKey, {}>>;
    MuiTypography?: Partial<import("@material-ui/core").StyleRules<import("@material-ui/core").TypographyClassKey, {}>>;
};
export default MUI_STYLE_OVERRIDES;
